# Generated by Django 5.0.7 on 2024-07-22 00:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_rename_post_registrationpost'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RegistrationPost',
            new_name='Post',
        ),
    ]
